# Generated by Django 3.0 on 2022-04-12 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loanApplications', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SolicitudPrestamo',
            new_name='LoanApplication',
        ),
    ]
