# Generated by Django 3.0 on 2022-04-11 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudPrestamo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.IntegerField()),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('genero', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('monto', models.IntegerField()),
                ('estaAprobado', models.BooleanField(default=False)),
            ],
        ),
    ]
